### ISSUE TITLE
Small problems at using

### ISSUE THREAD

**Issue by ralfdreibrodt** [gflohr/einvoice-eu#65]
I had three problems during installation and creating my first invoice:
a) "Full-Fledged Example" from README:

> $ curl -v -X POST \
>     http://localhost:3000/api/invoice/transform-and-create/UBL \
>     -F lang=de
>     -F mapping=@contrib/mappings/default-invoice.yaml \

In line three the backslash is missing

b) https://www.guido-flohr.net/creating-electronic-invoices-with-free-and-open-source-software/
_This will create a directory dist that you can copy wherever you like._
Whenever I move the dist directory, I get an error:
> node:internal/modules/cjs/loader:1137
>   throw err;
>   ^
> 
> Error: Cannot find module '@esgettext/runtime'
> Require stack:
> - /var/www/dist/src/main.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
>     at Module._load (node:internal/modules/cjs/loader:975:27)
>     at Module.require (node:internal/modules/cjs/loader:1225:19)
>     at require (node:internal/modules/helpers:177:18)
>     at Object.<anonymous> (/var/www/dist/src/main.js:3:19)
>     at Module._compile (node:internal/modules/cjs/loader:1356:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
>     at Module.load (node:internal/modules/cjs/loader:1197:32)
>     at Module._load (node:internal/modules/cjs/loader:1013:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/var/www/dist/src/main.js' ]
> }
> 
> Node.js v18.19.0
> 

Without moving dist it is working, until:
c) changing the format to Factur-X-XRechnung
The software is crashing:

> /var/www/e-invoice-eu-main/dist/src/format/format-factur-x.service.js:239
>         const hash = await crypto.subtle.digest('SHA-512', encoder.encode(data));
>                      ^
> 
> ReferenceError: crypto is not defined
>     at FormatFacturXXRechnungService.setTrailerInfoID (/var/www/e-invoice-eu-main/dist/src/format/format-factur-x.service.js:239:22)
>     at FormatFacturXXRechnungService.createPDFA (/var/www/e-invoice-eu-main/dist/src/format/format-factur-x.service.js:172:14)
>     at FormatFacturXXRechnungService.generate (/var/www/e-invoice-eu-main/dist/src/format/format-factur-x.service.js:88:20)
>     at async InvoiceController.create (/var/www/e-invoice-eu-main/dist/src/invoice/invoice.controller.js:52:30)
> 
> Node.js v18.19.0
> 
After googling the error message, I added before the above line 239 this:
`const crypto = require('crypto');`
Now the software is not crashing anymore and the validator says everthing is correct, but I have no idea, whether that's true.

**Comment by gflohr** [comment]
About the validation, please read this documentation: https://github.com/gflohr/e-invoice-eu/blob/main/contrib/validators/README.md You should definitely validate your invoices before sending them. It is very unlikely that they are correct from the beginning.

I will take care of the other two problems next week. I am currently travelling.

**Comment by gflohr** [comment]
Until I fix the other two issues, you may consider to use the containerized version on dockerhub.

**Comment by gflohr** [comment]
> I had three problems during installation and creating my first invoice: a) "Full-Fledged Example" from README:
> 
> > $ curl -v -X POST 
> > http://localhost:3000/api/invoice/transform-and-create/UBL 
> > -F lang=de
> > -F mapping=@contrib/mappings/default-invoice.yaml \
> 
> In line three the backslash is missing

Fixed.

**Comment by gflohr** [comment]
> b) https://www.guido-flohr.net/creating-electronic-invoices-with-free-and-open-source-software/ _This will create a directory dist that you can copy wherever you like._ Whenever I move the dist directory, I get an error:

Sorry, my bad, you can *not* move the directory.

**Comment by gflohr** [comment]
I cannot reproduce the reference error for `crypto` but I have tried to fix it. Can you update to the latest commit and try again?

**Comment by ralfdreibrodt** [comment]
Thank you for your changes. The documentation is now correct.

> I cannot reproduce the reference error for crypto but I have tried to fix it.
> Can you update to the latest commit and try again?

It still does not work, but the error message changed. Btw this is a Debian 12.

> [Nest] 899611  - 01/08/2025, 1:32:45 PM     LOG [Request] POST /api/invoice/create/Factur-X-XRechnung 201 - 171ms
> /var/www/e-invoice-eu-main/dist/format/format-factur-x.service.js:240
>         const hash = await crypto_1.default.subtle.digest('SHA-512', encoder.encode(data));
>                                             ^
> 
> TypeError: Cannot read properties of undefined (reading 'subtle')
>     at FormatFacturXXRechnungService.setTrailerInfoID (/var/www/e-invoice-eu-main/dist/format/format-factur-x.service.js:240:45)
>     at FormatFacturXXRechnungService.createPDFA (/var/www/e-invoice-eu-main/dist/format/format-factur-x.service.js:173:14)
>     at FormatFacturXXRechnungService.generate (/var/www/e-invoice-eu-main/dist/format/format-factur-x.service.js:89:20)
>     at async InvoiceController.create (/var/www/e-invoice-eu-main/dist/invoice/invoice.controller.js:52:30)
> 
> Node.js v18.19.0
>

**Comment by gflohr** [comment]
I could reproduce the issue with node 18. It should now work with node 18, 20, and 22.

Can you try again?

**Comment by ralfdreibrodt** [comment]
Thank you, it is working now!

**Comment by gflohr** [comment]
Thank you for reporting the problems!
